### PR TITLE
RF: make offset and length into lists

### PR DESCRIPTION
**Pull request by matthew-brett**
As discussed on gitter channel.

### CODE REVIEW

**Comment by MarcCote** [comment]
The up-to-date test for the save/load is failing. Loading a `ArraySequence` from disk converts `_lengths` and `_offsets` to ndarrays.

**Comment by matthew-brett** [comment]
I futzed around for a while.  The append method is still slower than your coroutines.  Time on my machine, for:

Coroutines:

```
$ python nibabel/benchmarks/bench_streamlines.py 
Old: Loaded 5,000 streamlines in   3.07

New: Loaded 5,000 streamlines in    4.2
Speedup of 0.73
Old: Loaded 5,000 streamlines with scalars in   5.25
New: Loaded 5,000 streamlines with scalars in   7.47
Speedup of 0.702811
```

Loading arrays with new `append` method:

```
diff --git a/nibabel/streamlines/array_sequence.py b/nibabel/streamlines/array_sequence.py
index 8e466c1..b8f5c28 100644
--- a/nibabel/streamlines/array_sequence.py
+++ b/nibabel/streamlines/array_sequence.py
@@ -407,17 +407,8 @@ def create_arraysequences_from_generator(gen, n):
         Number of :class:`ArraySequences` object to create.
     """
     seqs = [ArraySequence() for _ in range(n)]
-    coroutines = [seq._extend_using_coroutine() for seq in seqs]
-
-    for coroutine in coroutines:
-        coroutine.send(None)
-
     for data in gen:
-        for i, coroutine in enumerate(coroutines):
+        for i, seq in enumerate(seqs):
             if data[i].nbytes > 0:
-                coroutine.send(data[i])
-
-    for coroutine in coroutines:
-        coroutine.close()
-
+                seq.append(data[i])
     return seqs
```

```
$ python nibabel/benchmarks/bench_streamlines.py 
Old: Loaded 5,000 streamlines in   3.12

New: Loaded 5,000 streamlines in    5.3
Speedup of 0.59
Old: Loaded 5,000 streamlines with scalars in   5.33
New: Loaded 5,000 streamlines with scalars in  13.09
Speedup of 0.407181
```

I think the difference for the coroutines is that they avoid reloading the function state at each call.  The buffering is different too, but I don't think that makes a big difference.

**Comment by MarcCote** [comment]
For sure, `create_arraysequences_from_generator` is way cleaner that way.

I just remember why I was using ndarray instead of list for `_lengths` and `_offsets`. In Cython it easier to have a memoryview of ndarrays. In Dipy's new PR I'm using them all the time. Maybe simple readonly properties that converts them in ndarray will do, but I have to check.

**Comment by Garyfallidis** [comment]
Yes, we need the ndarrays for cython!

**Comment by matthew-brett** [comment]
How about calling `np.asarray` in Cython?

**Comment by matthew-brett** [comment]
If you are accessing these fields from Cython, I guess they should be public.

**Comment by MarcCote** [comment]
The np.asarray could not work as we modify these attributes directly from
Cython.

We are also accessing and modifying the _data.

**Comment by matthew-brett** [comment]
Could you point to some Cython code where this is happening?   Is there a reason you could not use the list with the usual Python / Cython syntax?  It's surprising to me that this would be a real bottleneck, but I'm sure the code will be useful to think about the problem.

**Comment by MarcCote** [comment]
In the file
https://github.com/MarcCote/dipy/blob/enh_support_compactlist/dipy/tracking/streamlinespeed.pyx

in function set_number_of_points which calls
c_set_number_of_points_from_arraysequence

**Comment by matthew-brett** [comment]
That code looks as if it could deal with lists fairly easily with np.array calls - not so?

**Comment by matthew-brett** [comment]
I think this PR isn't going to work - the behavior of `append` depends on `append` knowing that it is the only routine that could be updating the object (via `self._next_offset`).  But - this isn't true - the coroutines could also be in action, or you could be updating the internal state via Cython.   I think the fix is to have an explicit field to say - I am mid-build, and can rely on my state - that is unset by default.  This will make it easier to use arrays for the onsets and lengths.

**Pull request closed without merging**
